apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install-task
spec:
  steps:
    - name: install
      image: node:16
      script: |
        npm install

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-test-task
spec:
  steps:
    - name: test
      image: node:16
      script: |
        npm install
        npx jasmine
